if(NOT IS_ABSOLUTE ${OPENSSL_SSL_LIBRARY})
    set(OPENSSL_SSL_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/${OPENSSL_SSL_LIBRARY}")
endif()

if(NOT IS_ABSOLUTE ${OPENSSL_INCLUDE_DIR})
    set(OPENSSL_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/${OPENSSL_INCLUDE_DIR}")
endif()

if(NOT IS_ABSOLUTE ${OPENSSL_CRYPTO_LIBRARY})
    set(OPENSSL_CRYPTO_LIBRARY "${CMAKE_CURRENT_SOURCE_DIR}/${OPENSSL_CRYPTO_LIBRARY}")
endif()

add_library(OpenSSL::SSL STATIC IMPORTED)
set_property(TARGET OpenSSL::SSL PROPERTY IMPORTED_LOCATION ${OPENSSL_SSL_LIBRARY})
set_property(TARGET OpenSSL::SSL PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${OPENSSL_INCLUDE_DIR})

add_library(OpenSSL::Crypto STATIC IMPORTED)
set_property(TARGET OpenSSL::Crypto PROPERTY IMPORTED_LOCATION ${OPENSSL_CRYPTO_LIBRARY})
set_property(TARGET OpenSSL::Crypto PROPERTY INTERFACE_INCLUDE_DIRECTORIES ${OPENSSL_INCLUDE_DIR})

set(OPENSSL_FOUND TRUE)
